### ISSUE TITLE
Issue importing dashboard

### ISSUE THREAD

**Issue by zyberetta** [dragoangel/parsedmarc-dockerized#7]
When I try to import dashboard, Kibana states the file cannot be processed.

The issue occurs because kibana and elastic search version is too old and must be upgraded to version 7.16.2

In docker-compose.yaml I tried to use latest version.

Now I can import the export.ndjson successfully but dashboards are stating index patterns are missing.

can you help fix these issues?

**Comment by mkilijanek** [comment]
I have created pull request with changes to upgrade elasticsearch and kibana to version 7.17.0

**Comment by justgosh** [comment]
I'm seeing the same error

Sorry, there was an error
The file could not be processed.

Console is reporting "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "parsedmarc", "node.name": "13c30e0efe5e", "message": "flood stage disk watermark [95%] exceeded on [s8dDbQZ9SEGGCl-EtAomog][13c30e0efe5e][/usr/share/elasticsearch/data/nodes/0] free: 255.1mb[2.5%], all indices on this node will be marked read-only",

kibana           | {"type":"response","@timestamp":"2022-03-28T02:37:06Z","tags":[],"pid":7,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"192.168.16.175","x-real-ip":"192.168.16.128","x-forwarded-for":"192.168.16.128","connection":"close","content-length":"408","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"","dnt":"1","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36","kbn-version":"7.9.3","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://192.168.16.175","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://192.168.16.175/app/management/kibana/objects","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.20.0.5","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36","referer":"https://192.168.16.175/app/management/kibana/objects"},"res":{"statusCode":200,"responseTime":17,"contentLength":9},"message":"POST /api/ui_metric/report 200 17ms - 9.0B"}
kibana           | {"type":"log","@timestamp":"2022-03-28T02:37:10Z","tags":["error","plugins","taskManager","taskManager"],"pid":7,"message":"Failed to poll for work: Error: Request Timeout after 30000ms"}
elasticsearch    | {"type": "server", "timestamp": "2022-03-28T02:37:18,130Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "parsedmarc", "node.name": "13c30e0efe5e", "message": "flood stage disk watermark [95%] exceeded on [s8dDbQZ9SEGGCl-EtAomog][13c30e0efe5e][/usr/share/elasticsearch/data/nodes/0] free: 255.1mb[2.5%], all indices on this node will be marked read-only", "cluster.uuid": "joKzQFO1Ts2LoiPzklV0bQ", "node.id": "s8dDbQZ9SEGGCl-EtAomog"  }
kibana           | {"type":"log","@timestamp":"2022-03-28T02:37:36Z","tags":["warning","plugins","kibanaUsageCollection","application-usage"],"pid":7,"message":"Failed to rollup transactional to daily entries"}
kibana           | {"type":"log","@timestamp":"2022-03-28T02:37:36Z","tags":["warning","plugins","kibanaUsageCollection","application-usage"],"pid":7,"message":"{ Error: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 429,\n  displayName: 'TooManyRequests',\n  message:\n   'index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];',\n  path:\n   '/.kibana/_doc/application_usage_transactional%3Ac0c0ea10-ae14-11ec-9a46-ed7178728a29',\n  query: { refresh: 'wait_for' },\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'cluster_block_exception',\n        reason:\n         'index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];' },\n     status: 429 },\n  statusCode: 429,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"cluster_block_exception\",\"reason\":\"index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\"}],\"type\":\"cluster_block_exception\",\"reason\":\"index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\"},\"status\":429}',\n  toString: [Function],\n  toJSON: [Function],\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 500,\n     payload:\n      { message: 'An internal server error occurred',\n        statusCode: 500,\n        error: 'Internal Server Error' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/generalError' }"}
kibana           | {"type":"response","@timestamp":"2022-03-28T02:37:38Z","tags":[],"pid":7,"method":"post","statusCode":422,"req":{"url":"/api/saved_objects/_import?overwrite=true","method":"post","headers":{"host":"192.168.16.175","x-real-ip":"192.168.16.128","x-forwarded-for":"192.168.16.128","connection":"close","content-length":"152292","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"","dnt":"1","content-type":"multipart/form-data; boundary=----WebKitFormBoundaryRyNuq9mKfhK2982b","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36","kbn-version":"7.9.3","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://192.168.16.175","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://192.168.16.175/app/management/kibana/objects","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.20.0.5","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36","referer":"https://192.168.16.175/app/management/kibana/objects"},"res":{"statusCode":422,"responseTime":102,"contentLength":9},"message":"POST /api/saved_objects/_import?overwrite=true 422 102ms - 9.0B"}
kibana           | {"type":"error","@timestamp":"2022-03-28T02:37:40Z","tags":["warning","process"],"pid":7,"level":"error","error":{"message":"Error: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: Error: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n    at emitWarning (internal/process/promises.js:97:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"Error: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
kibana           | {"type":"error","@timestamp":"2022-03-28T02:37:40Z","tags":["warning","process"],"pid":7,"level":"error","error":{"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)","name":"UnhandledPromiseRejectionWarning","stack":"Error: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: [cluster_block_exception] index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)"}
